import 'package:flutter/material.dart';
import 'package:ap_finale_project_front/Product.dart';

List<Product> fakeProducts = [
  Product(
    title: 'Smartphone X1',
    fullPrice: '1000',
    price: '800',
    rating: '4',
    backgroundColor: Colors.blueGrey,
    strcolor: 'BlueGrey',
    color: Colors.blueGrey,
    img: 'https://via.placeholder.com/150',
    discount: 20,
    isAmazingOffer: true,
    isTopProduct: true,
    stock: 25,
    soldCount: 100,
    productScore: 4.7,
    isLiked: true,
    category: 'Electronics',
    specs: ProductSpecs(
      phoneType: 'Android',
      model: 'X1 Pro',
      releaseDate: '2024-01-15',
      dimensions: '6.2 x 3.1 x 0.3 inches',
      features: ['5G', '128GB Storage', 'Triple Camera'],
    ),
  ),
  Product(
    title: 'Wireless Earbuds Z2',
    fullPrice: '150',
    price: '120',
    rating: '4',
    backgroundColor: Colors.redAccent,
    strcolor: 'RedAccent',
    color: Colors.redAccent,
    img: 'https://via.placeholder.com/150',
    discount: 15,
    isAmazingOffer: false,
    isTopProduct: true,
    stock: 50,
    soldCount: 200,
    productScore: 4.3,
    isLiked: false,
    category: 'Accessories',
    specs: ProductSpecs(
      phoneType: '',
      model: 'Z2',
      releaseDate: '2023-10-10',
      dimensions: '1.5 x 1 x 0.5 inches',
      features: ['Bluetooth 5.2', 'Noise Cancellation', 'Water Resistant'],
    ),
  ),
  Product(
    title: 'Gaming Laptop Pro 17',
    fullPrice: '2500',
    price: '2000',
    rating: '4',
    backgroundColor: Colors.black,
    strcolor: 'Black',
    color: Colors.black,
    img: 'https://via.placeholder.com/150',
    discount: 20,
    isAmazingOffer: true,
    isTopProduct: true,
    stock: 10,
    soldCount: 50,
    productScore: 4.9,
    isLiked: true,
    category: 'Computers',
    specs: ProductSpecs(
      phoneType: '',
      model: 'Pro 17',
      releaseDate: '2024-03-01',
      dimensions: '15.6 x 10 x 0.8 inches',
      features: ['RTX 4080', '16GB RAM', '1TB SSD'],
    ),
  ),
  Product(
    title: 'Smartwatch Gen 3',
    fullPrice: '300',
    price: '250',
    rating: '4',
    backgroundColor: Colors.teal,
    strcolor: 'Teal',
    color: Colors.teal,
    img: 'https://via.placeholder.com/150',
    discount: 17,
    isAmazingOffer: false,
    isTopProduct: true,
    stock: 30,
    soldCount: 90,
    productScore: 4.5,
    isLiked: false,
    category: 'Wearables',
    specs: ProductSpecs(
      phoneType: '',
      model: 'Gen 3',
      releaseDate: '2023-12-20',
      dimensions: '1.7 x 1.7 x 0.4 inches',
      features: ['Heart Rate Monitor', 'GPS', 'Water Resistant'],
    ),
  ),
  Product(
    title: '4K Smart TV 50"',
    fullPrice: '800',
    price: '650',
    rating: '3',
    backgroundColor: Colors.purple,
    strcolor: 'Purple',
    color: Colors.purple,
    img: 'https://via.placeholder.com/150',
    discount: 18,
    isAmazingOffer: true,
    isTopProduct: false,
    stock: 40,
    soldCount: 150,
    productScore: 4.8,
    isLiked: true,
    category: 'Home Appliances',
    specs: ProductSpecs(
      phoneType: '',
      model: 'UHD-50',
      releaseDate: '2023-09-15',
      dimensions: '44 x 25 x 3 inches',
      features: ['4K Display', 'HDR10', 'Smart OS'],
    ),
  ),
  Product(
    title: 'Gaming Chair XL',
    fullPrice: '300',
    price: '250',
    rating: '2',
    backgroundColor: Colors.green,
    strcolor: 'Green',
    color: Colors.green,
    img: 'https://via.placeholder.com/150',
    discount: 16,
    isAmazingOffer: false,
    isTopProduct: false,
    stock: 20,
    soldCount: 70,
    productScore: 4.2,
    isLiked: false,
    category: 'Furniture',
    specs: ProductSpecs(
      phoneType: '',
      model: 'XL Pro',
      releaseDate: '2024-02-01',
      dimensions: '24 x 30 x 50 inches',
      features: ['Adjustable Height', 'Ergonomic Design', 'Lumbar Support'],
    ),
  ),
  Product(
    title: 'Electric Toothbrush S1',
    fullPrice: '100',
    price: '80',
    rating: '1',
    backgroundColor: Colors.orange,
    strcolor: 'Orange',
    color: Colors.orange,
    img: 'https://via.placeholder.com/150',
    discount: 20,
    isAmazingOffer: false,
    isTopProduct: true,
    stock: 100,
    soldCount: 500,
    productScore: 4.3,
    isLiked: true,
    category: 'Personal Care',
    specs: ProductSpecs(
      phoneType: '',
      model: 'S1 Clean',
      releaseDate: '2022-05-10',
      dimensions: '1.2 x 1.2 x 8 inches',
      features: ['2-Min Timer', 'Replaceable Heads', 'Waterproof'],
    ),
  ),
  Product(
    title: 'Bluetooth Speaker BoomBox',
    fullPrice: '200',
    price: '170',
    rating: '0',
    backgroundColor: Colors.blue,
    strcolor: 'Blue',
    color: Colors.blue,
    img: 'https://via.placeholder.com/150',
    discount: 15,
    isAmazingOffer: true,
    isTopProduct: true,
    stock: 35,
    soldCount: 180,
    productScore: 4.9,
    isLiked: true,
    category: 'Audio',
    specs: ProductSpecs(
      phoneType: '',
      model: 'BoomBox',
      releaseDate: '2023-08-01',
      dimensions: '10 x 4 x 5 inches',
      features: ['Deep Bass', 'Bluetooth 5.1', '12 Hours Playtime'],
    ),
  ),
  Product(
    title: 'Smartphone X1',
    fullPrice: '1000',
    price: '800',
    rating: '5',
    backgroundColor: Colors.blueGrey,
    strcolor: 'BlueGrey',
    color: Colors.blueGrey,
    img: 'https://via.placeholder.com/150',
    discount: 20,
    isAmazingOffer: true,
    isTopProduct: true,
    stock: 25,
    soldCount: 100,
    productScore: 4.7,
    isLiked: true,
    category: 'Electronics',
    specs: ProductSpecs(
      phoneType: 'Android',
      model: 'X1 Pro',
      releaseDate: '2024-01-15',
      dimensions: '6.2 x 3.1 x 0.3 inches',
      features: ['5G', '128GB Storage', 'Triple Camera'],
    ),
  ),
  Product(
    title: 'Wireless Earbuds Z2',
    fullPrice: '150',
    price: '120',
    rating: '4',
    backgroundColor: Colors.redAccent,
    strcolor: 'RedAccent',
    color: Colors.redAccent,
    img: 'https://via.placeholder.com/150',
    discount: 15,
    isAmazingOffer: false,
    isTopProduct: true,
    stock: 50,
    soldCount: 200,
    productScore: 4.3,
    isLiked: false,
    category: 'Accessories',
    specs: ProductSpecs(
      phoneType: '',
      model: 'Z2',
      releaseDate: '2023-10-10',
      dimensions: '1.5 x 1 x 0.5 inches',
      features: ['Bluetooth 5.2', 'Noise Cancellation', 'Water Resistant'],
    ),
  ),
  Product(
    title: 'Gaming Laptop Pro 17',
    fullPrice: '2500',
    price: '2000',
    rating: '4',
    backgroundColor: Colors.black,
    strcolor: 'Black',
    color: Colors.black,
    img: 'https://via.placeholder.com/150',
    discount: 20,
    isAmazingOffer: true,
    isTopProduct: true,
    stock: 10,
    soldCount: 50,
    productScore: 4.9,
    isLiked: true,
    category: 'Computers',
    specs: ProductSpecs(
      phoneType: '',
      model: 'Pro 17',
      releaseDate: '2024-03-01',
      dimensions: '15.6 x 10 x 0.8 inches',
      features: ['RTX 4080', '16GB RAM', '1TB SSD'],
    ),
  ),
];
